<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
	  <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
	  <RootNamespace>Preferences</RootNamespace>
	  <UseWinUI>true</UseWinUI>
	  <AssemblyName>Preferences</AssemblyName>
	  <Nullable>enable</Nullable>
	  <Configurations>Debug;Release;DevDebug</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1721" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260416003" />
    <PackageReference Include="WinUIEx" Version="2.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\010_Common.csproj" />
    <ProjectReference Include="..\WinAPI\100_WinAPI.csproj" />
  </ItemGroup>

</Project>
