<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>SelectionToolbar</RootNamespace>
    <UseWinUI>true</UseWinUI>
    <AssemblyName>SelectionToolbar</AssemblyName>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;DevDebug</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1721" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260416003" />
    <PackageReference Include="Accessibility" Version="4.6.0-preview3.19128.7" />
    <PackageReference Include="WinUIEx" Version="2.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\010_Common.csproj" />
    <ProjectReference Include="..\WinAPI\100_WinAPI.csproj" />
    <ProjectReference Include="..\Preferences\040_Preferences.csproj" />
  </ItemGroup>

</Project>
